swagger: '2.0'
info:
  version: 1.0.1
  title: Ethereum wallet API
  description: Just simple Ethereum-based API for a crypto wallet.
  license:
    name: ISC
    url: https://choosealicense.com/licenses/isc/
host: 176.37.12.50:8364
schemes:
  - http
basePath: "/"
tags:
- name: Users
  description: API for users in the system
- name: Auth
  description: API for users login and registration
consumes:
- application/json
produces:
- application/json
paths:
  "/auth/login":
    post:
      tags:
      - Auth
      description: Login to use the API
      parameters:
      - name: Login
        in: body
        required: true
        description: Username
        schema:
          "$ref": "#/definitions/Login"
      produces:
      - application/json
      responses:
        '200':
          description: You were logged in successfully
          schema:
            "$ref": "#/definitions/Login"
  "/wallet/getBalance":
    parameters:
    - name: x-access-token
      in: header
      required: true
      description: Your token for the API. You can get it using /auth/login method
      type: string
    get:
      tags:
      - Wallet
      summary: Get your Ethereum balance
      responses:
        '200':
          description: Balance was get successfully
          schema:
            "$ref": "#/definitions/Balance"
  "/wallet/getTransactions":
    parameters:
    - name: x-access-token
      in: header
      required: true
      description: Your token for the API. You can get it using /auth/login method
      type: string
    get:
      tags:
      - Wallet
      summary: Get your Ethereum transactions
      responses:
        '200':
          description: Transactions was received successfully
          schema:
            "$ref": "#/definitions/Transactions"
        '401':
          description: Another response... (error)
  "/rates/ethUsd":
    parameters:
    - name: x-access-token
      in: header
      required: true
      description: Your token for the API. You can get it using /auth/login method
      type: string
    get:
      tags:
      - Rates
      summary: Get ETH/USD rate
      responses:
        '200':
          description: Rate was received successfully
          schema:
            "$ref": "#/definitions/Rates"
        '401':
          description: Another response... (error)
definitions:
  Login:
    required:
    - username
    - password
    properties:
      username:
        type: string
        uniqueItems: true
      password:
        type: string
  Balance:
    properties:
      status:
        type: string
      balance:
        type: integer
  Transactions:
    properties:
      status:
        type: string
      txs:
        type: object
  Rates:
    properties:
      status:
        type: string
      pair:
        type: string
      price:
        type: string
      change24h:
        type: string
